#!/usr/bin/env python3

# warning: this script was generated by a large language model

"""
Format the kernel sources: run clang-format, then restore `{ ... }` spacing.

Usage:
    misc/format.py                 # format all kernel and module sources
    misc/format.py FILE|DIR ...    # format only the given files/directories
    misc/format.py --check ...     # report files that need formatting (exit 1)

Needs at least clang-format version 22.
Override the clang-format binary with --clang-format or $CLANG_FORMAT.
"""

import argparse
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEFAULT_DIRS = ('kernel/source', 'kernel/interfaces', 'kernel/include', 'modules')

EXTS = ('.cpp', '.cppm', '.cc', '.cxx', '.c++', '.hpp', '.hh', '.hxx', '.h')

def _ends_with_word(out: list, word: str) -> bool:
    length = len(word)
    if len(out) < length or ''.join(out[-length:]) != word:
        return False
    if len(out) > length and (out[-length - 1].isalnum() or out[-length - 1] == '_'):
        return False
    return True

def transform(s: str) -> str:
    n = len(s)
    out: list[str] = []
    i = 0
    while i < n:
        c = s[i]

        if c == '/' and i + 1 < n and s[i + 1] == '/':
            j = s.find('\n', i)
            j = n if j == -1 else j
            out.extend(s[i:j]); i = j; continue

        if c == '/' and i + 1 < n and s[i + 1] == '*':
            j = s.find('*/', i + 2)
            j = n if j == -1 else j + 2
            out.extend(s[i:j]); i = j; continue

        if c == '"' and i > 0 and s[i - 1] == 'R':
            k = i + 1
            while k < n and s[k] != '(' and s[k] not in ' \t\r\n\\)':
                k += 1
            if k < n and s[k] == '(':
                term = ')' + s[i + 1:k] + '"'
                j = s.find(term, k + 1)
                j = n if j == -1 else j + len(term)
                out.extend(s[i:j]); i = j; continue

        if c == '"':
            j = i + 1
            while j < n:
                if s[j] == '\\':
                    j += 2; continue
                if s[j] == '"':
                    j += 1; break
                if s[j] == '\n':
                    break
                j += 1
            out.extend(s[i:j]); i = j; continue

        if c == "'":
            j = i + 1
            ok = False
            limit = min(n, i + 18)
            while j < limit:
                if s[j] == '\\':
                    j += 2; continue
                if s[j] == '\n':
                    break
                if s[j] == "'":
                    j += 1; ok = True; break
                j += 1
            if ok and j > i + 1:
                out.extend(s[i:j]); i = j; continue
            out.append(c); i += 1; continue

        if c == '{':
            k = i + 1
            while k < n and s[k] in ' \t':
                k += 1
            if (k >= n or s[k] in '\r\n'
                    or (s[k] == '\\' and (k + 1 >= n or s[k + 1] in '\r\n'))):
                out.append('{'); i += 1
            else:
                out.append('{'); out.append(' '); i = k
            continue

        if c == '}':
            k = len(out) - 1
            while k >= 0 and out[k] in ' \t':
                k -= 1
            if k < 0 or out[k] in '\r\n':
                out.append('}')
            else:
                del out[k + 1:]
                out.append(' '); out.append('}')
            i += 1
            if i < n and (s[i] == '('
                          or (s[i] == '.' and i + 1 < n and (s[i + 1].isalnum() or s[i + 1] == '_'))):
                out.append(' ')
            continue

        if c == '(' and _ends_with_word(out, 'volatile'):
            out.append(' '); out.append('('); i += 1; continue

        out.append(c); i += 1

    return ''.join(out)


def gather(paths) -> list[str]:
    files = []
    for p in paths:
        if os.path.isdir(p):
            for dirpath, _, names in os.walk(p):
                for name in names:
                    if name.endswith(EXTS):
                        files.append(os.path.join(dirpath, name))
        elif os.path.isfile(p):
            files.append(p)
        else:
            print(f'format: no such file or directory: {p}', file=sys.stderr)
    return sorted(set(files))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('paths', nargs='*',
                    help='files or directories to format (default: all kernel + module sources)')
    ap.add_argument('--check', action='store_true',
                    help='do not modify files; exit 1 if any would change')
    ap.add_argument('--clang-format', default=os.environ.get('CLANG_FORMAT', 'clang-format'),
                    help='clang-format binary to use (default: $CLANG_FORMAT or clang-format)')
    args = ap.parse_args()

    paths = args.paths or [os.path.join(ROOT, d) for d in DEFAULT_DIRS]
    files = gather(paths)
    if not files:
        print('format: no source files found', file=sys.stderr)
        return 1

    changed = []
    for path in files:
        try:
            with open(path, encoding='utf-8') as f:
                original = f.read()
        except (OSError, UnicodeDecodeError) as e:
            print(f'format: skip {path}: {e}', file=sys.stderr)
            continue
        try:
            cf = subprocess.run([args.clang_format, '--style=file', path],
                                capture_output=True, text=True, check=True).stdout
        except FileNotFoundError:
            print(f'format: clang-format not found: {args.clang_format}', file=sys.stderr)
            return 2
        except subprocess.CalledProcessError as e:
            print(f'format: clang-format failed on {path}:\n{e.stderr}', file=sys.stderr)
            return 2
        result = transform(cf)
        if result != original:
            changed.append(path)
            if not args.check:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(result)

    if args.check:
        if changed:
            print('needs formatting:')
            for p in changed:
                print(f'  {os.path.relpath(p, ROOT)}')
            return 1
        print(f'format: {len(files)} files OK')
        return 0

    print(f'format: {len(files)} files processed, {len(changed)} reformatted')
    return 0

if __name__ == '__main__':
    sys.exit(main())
