# Copyright (C) 2024-2025  ilobilo

if(NOT DEFINED ILOBILIX_ARCH OR ILOBILIX_ARCH STREQUAL "")
    set(ILOBILIX_ARCH "x86_64" CACHE STRING "Target architecture")
endif()
set_property(CACHE ILOBILIX_ARCH PROPERTY STRINGS "x86_64" "aarch64")